EXTRA_CFLAGS += -Isound/soc/codecs/

snd-soc-hi6xxx-fpga-test-objs :=hi6xxx_fpga_test.o
snd-soc-hi6555c-stub-objs :=hi6555c_stub.o

obj-$(CONFIG_SND_SOC_CODEC_STUB) += snd-soc-hi6xxx-fpga-test.o
obj-$(CONFIG_SND_SOC_CODEC_STUB) += snd-soc-hi6555c-stub.o