obj-$(CONFIG_JDI_HOST_TS_KIT) += bu21150.o
obj-$(CONFIG_JDI_HOST_TS_KIT) += input_mt_wrapper.o
obj-$(CONFIG_HUAWEI_THP) += huawei_thp_attr.o
obj-$(CONFIG_HUAWEI_THP) += huawei_thp_core.o
obj-$(CONFIG_HUAWEI_THP) += huawei_thp_mt_wrapper.o
obj-$(CONFIG_HUAWEI_THP_NOVATECH) += novatech.o
