ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-$(CONFIG_HUAWEI_CAMERA_USE_OV8865) += ov8865.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX286HYBIRD) += imx286hybird.o
