ccflags-y += -I$(srctree)/drivers/hisi/mntn/blackbox \
             -I$(srctree)/drivers/hisi/tzdriver/libhwsecurec \
             -I$(srctree)/drivers/hisi/ddrc \
             -Wall -Werror

obj-$(CONFIG_HISI_DMSS_PT) += dmss_pt_drv.o dmss_pt_dump.o
