ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y					+= entropy_common.o
obj-y					+= error_private.o
obj-y					+= xxhash.o
obj-y					+= zstd_common.o
obj-y					+= zstd_decompress.o
obj-y					+= fse_decompress.o
obj-y					+= huf_decompress.o