#goodix gt1x
obj-$(CONFIG_GOODIX_GT1X_TS_KIT) += gt1x.o
obj-$(CONFIG_GOODIX_GT1X_TS_KIT) += gt1x_update.o
obj-$(CONFIG_GOODIX_GT1X_TS_KIT) += gt1x_test.o
obj-$(CONFIG_GOODIX_GT1X_TS_KIT) += gt1x_tools.o

